const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dataPath = path.join(root, 'data', 'axis-data.json');
const outputPath = path.join(root, 'src', 'generated', 'axis-data.js');

const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(
  outputPath,
  `// Generated by scripts/build-data.cjs. Do not edit by hand.\nwindow.axisData = ${JSON.stringify(data, null, 2)};\n`,
  'utf8',
);

console.log(
  `Generated src/generated/axis-data.js: ${Object.keys(data.charAssets || {}).length} characters, ${(data.orderedChars || []).length} ordered entries.`,
);
